# Generated by Django 4.2.6 on 2024-06-19 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
