# Generated by Django 4.2.8 on 2024-07-07 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakaopay', '0002_remove_kakaopay_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='kakaopay',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kakaopay',
            name='point',
            field=models.CharField(max_length=100),
        ),
    ]
