# Generated by Django 4.2.8 on 2024-07-07 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakaopay', '0003_kakaopay_price_alter_kakaopay_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='kakaopay',
            name='pay_status',
            field=models.CharField(default='ready', max_length=100),
        ),
    ]
